"""
amp.logging.decision_logger
---------------------------
External, optional logging of AMP Decision Records.

Design decisions:
- Logging is EXTERNAL to the protocol core.
  AMP never logs autonomously — the caller decides if and when to log.
  This is why this module lives in amp/logging/, not amp/core/.

- The function accepts a trace_id generated by the caller (e.g. uuid4).
  AMP does not generate trace IDs internally to keep the core stateless.

- We use .jsonl (newline-delimited JSON) for the log file because:
  * each line is a valid, self-contained JSON object
  * append-only writes are safe under concurrent access
  * easy to tail, grep, and stream into any log aggregator

- audit.py is now deprecated. This module is its replacement with a
  simpler signature aligned to the example flow.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from amp.config import MAX_ID_LENGTH

LOG_PATH = Path("logs/decisions.jsonl")

# Performance optimization: ensure the log directory exists once at module load
# to avoid redundant syscalls during frequent logging operations.
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)


def write_decision_log(
    trace_id: str,
    decision_record: Dict[str, Any],
) -> None:
    """
    Append a decision record to the audit log.

    Parameters
    ----------
    trace_id        : external correlation ID (generated by the caller)
    decision_record : the dict produced by build_decision_record()
    """
    if not isinstance(trace_id, str):
        raise ValueError(f"trace_id must be a string, got {type(trace_id)}")
    if len(trace_id) > MAX_ID_LENGTH:
        raise ValueError(f"trace_id exceeds maximum length of {MAX_ID_LENGTH}")

    # ⚡ Bolt: Performance Optimization
    # Reuse the timestamp from the decision record to avoid a redundant syscall.
    # This also ensures the log entry and the record have perfectly synchronized timestamps.

    entry = {
        "ts": decision_record.get("ts"),
        "trace_id": trace_id,
        "record": decision_record,
    }

    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, ensure_ascii=False) + "\n")
