"""
amp.logging.decision_logger
---------------------------
External, optional logging of AMP Decision Records.

Design decisions:
- Logging is EXTERNAL to the protocol core.
  AMP never logs autonomously — the caller decides if and when to log.
  This is why this module lives in amp/logging/, not amp/core/.

- The function accepts a trace_id generated by the caller (e.g. uuid4).
  AMP does not generate trace IDs internally to keep the core stateless.

- We use .jsonl (newline-delimited JSON) for the log file because:
  * each line is a valid, self-contained JSON object
  * append-only writes are safe under concurrent access
  * easy to tail, grep, and stream into any log aggregator

- audit.py is now deprecated. This module is its replacement with a
  simpler signature aligned to the example flow.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

LOG_PATH = Path("logs/decisions.jsonl")


def write_decision_log(
    trace_id: str,
    decision_record: Dict[str, Any],
) -> None:
    """
    Append a decision record to the audit log.

    Parameters
    ----------
    trace_id        : external correlation ID (generated by the caller)
    decision_record : the dict produced by build_decision_record()
    """
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "trace_id": trace_id,
        "record": decision_record,
    }

    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, ensure_ascii=False) + "\n")
